[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "v4-core/=lib/v4-core/src/",
    "v4-periphery/=lib/v4-periphery/src/",
    "forge-std/=lib/v4-core/lib/forge-std/src/",
    "ds-test/=lib/v4-core/lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=lib/v4-core/lib/openzeppelin-contracts/"
]

# Optimization settings
optimizer = true
optimizer_runs = 2_000  # Increased from 200 for better gas optimization

# Via IR settings
via_ir = true  # Enable IR-based codegen
evm_version = "cancun"  # Specify EVM version for better optimization

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
